### ISSUE TITLE
Testing setup

### ISSUE THREAD

**Issue by JensGroth** [dfinity/ic-staking-documentation#9]
It is good practice to test your backup recovery. I for instance private key recovery using keysmith (by entering into a different file and running  keysmith private-key -f testbackupseed.txt -o testprivate.pem). Wonder if we should describe that as well in the guide; might also give the user some insight into what the seed phrase does.

**Comment by dprats** [comment]
@JensGroth does this address your suggestion? https://dfinity.github.io/ic-staking-documentation/7-faq/7-1-recreate-private-key.html

**Comment by JensGroth** [comment]
Yes it does. One extra we could do is insert a reference in the earlier setup docs that users can use these steps to test their ability to recover the private key and account number.
